dense_embedding:
  package: "fastembed"
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  params:
    size: 384
    distance: "Cosine"
    on_disk: true
    quantization_config:
      binary:
        always_ram: true

sparse_embedding:
  package: "fastembed"
  model_name: "Qdrant/bm25"
  params: {}

late_interaction_embedding:
  package: "fastembed"
  model_name: "answerdotai/answerai-colbert-small-v1"
  params:
    size: 96
    distance: "Cosine"
    on_disk: true
    multivector_config:
      comparator: "MAX_SIM"

# --- General Pipeline Settings ---
multi_tenant: true
replication_factor: 2
shard_number: 3
partition_config:
  field: "tenant_id"
  type: "keyword"
  on_disk: true