name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "~/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtualenv and install deps
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
      
      - name: Start Qdrant cluster
        run: |
          docker compose up -d
          # Give time for the cluster to initialize fully
          sleep 30
          
      - name: Check cluster status
        run: |
          curl http://localhost:6333/cluster
          
      - name: Run integration tests
        run: |
          source .venv/bin/activate
          python -m pytest tests/integration/ -v
          
      - name: Clean up
        if: always()
        run: |
          docker compose down -v
